### PR TITLE
Little more fixes and improvements...

### PR DESCRIPTION
**Pull request by Meychi**
...and now haxelib points back to you again. I will submit this to haxelib and follow with necessary bug fixes but atm i think i'm finished with this :)

### CODE REVIEW

**Comment by jgranick** [comment]
Sorry, I don't know why I never saw this? Not sure what the best way to make sure I "see" everything on Github really is!

Great to see that buildhx is of value, are you still working with this?

**Comment by Meychi** [comment]
Not actively but i use my master version for my projects. I did submit the haxelib version, how I can make it so that you can too?

**Comment by jgranick** [comment]
I thought that I had already submitted "buildhx", but perhaps in the Haxe 2 days :smile:

If you submit a new version that includes "singmajesty" as a user, then we both should be able to update it

**Comment by Meychi** [comment]
Ok i will do that and maybe we could then merge my fork back where it belongs to :)

**Pull request closed without merging**
